In [1]:
from arcgis.gis import GIS
gis = GIS("home")

In [2]:
from arcgis.features import FeatureLayer
from arcgis.geoenrichment import Country

### Connect to the Census Bureau's API and retrieve the ACS 5-year dataset for 2021

In [3]:
import cenpy
import pandas as pd
import arcpy

c = cenpy.remote.APIConnection('ACSDT5Y2021')

C:\Users\eli12899\AppData\Roaming\Python\Python39\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [4]:
api_database = 'ACSDT5Y2021'
cenpy.explorer.explain(api_database)

{'American Community Survey: 5-Year Estimates: Detailed Tables 5-Year': 'The American Community Survey (ACS) is an ongoing survey that provides data every year -- giving communities the current information they need to plan investments and services. The ACS covers a broad range of topics about social, economic, demographic, and housing characteristics of the U.S. population. Summary files include the following geographies: nation, all states (including DC and Puerto Rico), all metropolitan areas, all congressional districts, all counties, all places, and all tracts and block groups. Summary files contain the most detailed cross-tabulations, many of which are published down to block groups. The data are population and housing counts. There are over 64,000 variables in this dataset.'}

## Economic distress index

#Economic distress index using 2017-2021 American Community Survey (ACS) 5-year county level estimates. The index will include the following variables:

Percent households with $30,000 or less income

Percent population with less than a High School degree for population 25 Years and Over

Percent population living below poverty in the past 12 months

Percent unemployed for the population 16 Years and Over

Percent households with cash public assistance or Food Stamps/SNAP

Percent households with Supplemental Security Income (SSI)

In [5]:
data_raw = ['B19001_001', # full households
            'B19001_002' , # less than 10k
            'B19001_003' , # between 10-14k
            'B19001_004' , # between 15-19k
            'B19001_005' , # between 20-24k
            'B19001_006' , # between 25-29k
    
            'B19001B_001', # african american total households
                'B19001B_002' , # less than 10k
                'B19001B_003' , # between 10-14k
                'B19001B_004' , # between 15-19k
                'B19001B_005' , # between 20-24k
                'B19001B_006' , # between 25-29k
                
            'B19001C_001' , # american indian and alaska native total households
                    'B19001C_002' , # less than 10k
                    'B19001C_003' , # between 10-14k
                    'B19001C_004' , # between 15-19k
                    'B19001C_005' , # between 20-24k
                    'B19001C_006' , # between 25-29k

            'B19001D_001' , # asian total households
                    'B19001D_002' , # less than 10k
                    'B19001D_003' , # between 10-14k
                    'B19001D_004' , # between 15-19k
                    'B19001D_005' , # between 20-24k
                    'B19001D_006' , # between 25-29k
                
            'B19001E_001' , # native hawaiian or pacific islander total households
                    'B19001E_002' , # less than 10k
                    'B19001E_003' , # between 10-14k
                    'B19001E_004' , # between 15-19k
                    'B19001E_005' , # between 20-24k
                    'B19001E_006' , # between 25-29k
                
            'B19001H_001' , # nonhispanic white total households
                    'B19001H_002' , # less than 10k
                    'B19001H_003' , # between 10-14k
                    'B19001H_004' , # between 15-19k
                    'B19001H_005' , # between 20-24k
                    'B19001H_006' , # between 25-29k
            
            'B19001I_001' , # hispanic or latino total households
                    'B19001I_002' , # less than 10k
                    'B19001I_003' , # between 10-14k
                    'B19001I_004' , # between 15-19k
                    'B19001I_005' , # between 20-24k
                    'B19001I_006' , # between 25-29k
            
            'B15003_001' , #education attainment, total, for pop 25 years and over
                    'B15003_025', # Doctorate degree
                    'B15003_024', # Professional school degree
                    'B15003_023', # Master's degree
                    'B15003_022', # Bachelor's degree
                    'B15003_021', # Associate's degree
                    'B15003_020', # some college- 1 or more year..
                    'B15003_019', # some college- less than 1 year
                    'B15003_018', # GED or alternative credential
                    'B15003_017', # high school diploma
            
            'B17001_001', # POVERTY STATUS IN THE PAST 12 MONTHS
                    'B17001_002', # Income in the past 12 months below poverty level
            
            'B23025_002', # In Labor Force- FOR THE POPULATION 16 YEARS and over
                    'B23025_005', # Unemployed
            
            'B19058_002', # With cash public assistance or Food Stamps/SNAP
                    'B19058_001', #Total estimate
            
            'B19056_002', # With Supplemental Security Income (SSI)
                    'B19056_001', #Total estimate       
           ]

In [6]:
data_raw

['B19001_001', 'B19001_002', 'B19001_003', 'B19001_004', 'B19001_005', 'B19001_006', 'B19001B_001', 'B19001B_002', 'B19001B_003', 'B19001B_004', 'B19001B_005', 'B19001B_006', 'B19001C_001', 'B19001C_002', 'B19001C_003', 'B19001C_004', 'B19001C_005', 'B19001C_006', 'B19001D_001', 'B19001D_002', 'B19001D_003', 'B19001D_004', 'B19001D_005', 'B19001D_006', 'B19001E_001', 'B19001E_002', 'B19001E_003', 'B19001E_004', 'B19001E_005', 'B19001E_006', 'B19001H_001', 'B19001H_002', 'B19001H_003', 'B19001H_004', 'B19001H_005', 'B19001H_006', 'B19001I_001', 'B19001I_002', 'B19001I_003', 'B19001I_004', 'B19001I_005', 'B19001I_006', 'B15003_001', 'B15003_025', 'B15003_024', 'B15003_023', 'B15003_022', 'B15003_021', 'B15003_020', 'B15003_019', 'B15003_018', 'B15003_017', 'B17001_001', 'B17001_002', 'B23025_002', 'B23025_005', 'B19058_002', 'B19058_001', 'B19056_002', 'B19056_001']

In [7]:
# Estimates end in an "E" 
data_E = [i+'E' for i in data_raw]
data_E

['B19001_001E', 'B19001_002E', 'B19001_003E', 'B19001_004E', 'B19001_005E', 'B19001_006E', 'B19001B_001E', 'B19001B_002E', 'B19001B_003E', 'B19001B_004E', 'B19001B_005E', 'B19001B_006E', 'B19001C_001E', 'B19001C_002E', 'B19001C_003E', 'B19001C_004E', 'B19001C_005E', 'B19001C_006E', 'B19001D_001E', 'B19001D_002E', 'B19001D_003E', 'B19001D_004E', 'B19001D_005E', 'B19001D_006E', 'B19001E_001E', 'B19001E_002E', 'B19001E_003E', 'B19001E_004E', 'B19001E_005E', 'B19001E_006E', 'B19001H_001E', 'B19001H_002E', 'B19001H_003E', 'B19001H_004E', 'B19001H_005E', 'B19001H_006E', 'B19001I_001E', 'B19001I_002E', 'B19001I_003E', 'B19001I_004E', 'B19001I_005E', 'B19001I_006E', 'B15003_001E', 'B15003_025E', 'B15003_024E', 'B15003_023E', 'B15003_022E', 'B15003_021E', 'B15003_020E', 'B15003_019E', 'B15003_018E', 'B15003_017E', 'B17001_001E', 'B17001_002E', 'B23025_002E', 'B23025_005E', 'B19058_002E', 'B19058_001E', 'B19056_002E', 'B19056_001E']

In [8]:
data= c.query(['NAME' , 'GEO_ID', 'B19001_001E', 'B19001_002E', 'B19001_003E', 'B19001_004E', 'B19001_005E', 'B19001_006E', 'B19001B_001E', 'B19001B_002E', 'B19001B_003E', 'B19001B_004E', 'B19001B_005E', 'B19001B_006E', 'B19001C_001E', 'B19001C_002E', 'B19001C_003E', 'B19001C_004E', 'B19001C_005E', 'B19001C_006E', 'B19001D_001E', 'B19001D_002E', 'B19001D_003E', 'B19001D_004E', 'B19001D_005E', 'B19001D_006E', 'B19001E_001E', 'B19001E_002E', 'B19001E_003E', 'B19001E_004E', 'B19001E_005E', 'B19001E_006E', 'B19001H_001E', 'B19001H_002E', 'B19001H_003E', 'B19001H_004E', 'B19001H_005E', 'B19001H_006E', 'B19001I_001E', 'B19001I_002E', 'B19001I_003E', 'B19001I_004E', 'B19001I_005E', 'B19001I_006E', 'B15003_001E', 'B15003_025E', 'B15003_024E', 'B15003_023E', 'B15003_022E', 'B15003_021E', 'B15003_020E', 'B15003_019E', 'B15003_018E', 'B15003_017E', 'B17001_001E', 'B17001_002E', 'B23025_002E', 'B23025_005E', 'B19058_002E', 'B19058_001E', 'B19056_002E', 'B19056_001E' , ], geo_unit='county', geo_filter={'state': '*'})

data.head(5)

                      NAME          GEO_ID  ... B19056_002E B19056_001E
0  Autauga County, Alabama  0500000US01001  ...        1325       21856
1  Baldwin County, Alabama  0500000US01003  ...        4007       87190
2  Barbour County, Alabama  0500000US01005  ...         963        9088
3     Bibb County, Alabama  0500000US01007  ...         480        7083
4   Blount County, Alabama  0500000US01009  ...        1862       21300

[5 rows x 64 columns]

In [9]:
data[data_E] = data[data_E].astype('int') # convert downloaded data to integers

In [10]:
data = pd.DataFrame(data)
data.head()

                      NAME          GEO_ID  ...  B19056_002E  B19056_001E
0  Autauga County, Alabama  0500000US01001  ...         1325        21856
1  Baldwin County, Alabama  0500000US01003  ...         4007        87190
2  Barbour County, Alabama  0500000US01005  ...          963         9088
3     Bibb County, Alabama  0500000US01007  ...          480         7083
4   Blount County, Alabama  0500000US01009  ...         1862        21300

[5 rows x 64 columns]

In [ ]:
data_df['county_ID'] = economic_distress_index_df['GEO_ID'].str[9:]

In [11]:
data.shape

(3221, 64)

In [12]:
data.to_csv("C:/Users/eli12899/Documents/ArcGIS/Projects/Economic Distress Index_County level_ACS 2021/DATA/all_econ_distress.csv")

## CREATE THE ECONOMIC DISTRESS INDEX

In [13]:
economic_distress_index_df = data.filter(['NAME', 'GEO_ID'])
economic_distress_index_df.head(5)

                      NAME          GEO_ID
0  Autauga County, Alabama  0500000US01001
1  Baldwin County, Alabama  0500000US01003
2  Barbour County, Alabama  0500000US01005
3     Bibb County, Alabama  0500000US01007
4   Blount County, Alabama  0500000US01009

In [14]:
economic_distress_index_df['county_ID'] = economic_distress_index_df['GEO_ID'].str[9:]
economic_distress_index_df.head(5)

                      NAME          GEO_ID county_ID
0  Autauga County, Alabama  0500000US01001     01001
1  Baldwin County, Alabama  0500000US01003     01003
2  Barbour County, Alabama  0500000US01005     01005
3     Bibb County, Alabama  0500000US01007     01007
4   Blount County, Alabama  0500000US01009     01009

In [15]:
economic_distress_index_df['county_ID'] = economic_distress_index_df['county_ID'].astype(str)

print(pd.DataFrame(economic_distress_index_df.dtypes))

                0
NAME       object
GEO_ID     object
county_ID  object

### Index Variables Percentage Calculations

#### LOW INCOME

In [16]:
# create a new column 'pct_less_than_$30K'
economic_distress_index_df['pct_less_than_$30K'] = data[['B19001_002E', 'B19001_003E', 'B19001_004E', 'B19001_005E', 'B19001_006E']].sum(axis=1) / data['B19001_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME          GEO_ID county_ID  pct_less_than_$30K
0  Autauga County, Alabama  0500000US01001     01001            0.260706
1  Baldwin County, Alabama  0500000US01003     01003            0.206147
2  Barbour County, Alabama  0500000US01005     01005            0.438050
3     Bibb County, Alabama  0500000US01007     01007            0.305520
4   Blount County, Alabama  0500000US01009     01009            0.275023

#### Percent with less than High School Degree

In [17]:
# create a new column 'pct_less_than_high_school'
economic_distress_index_df['pct_less_than_high_school'] = data[['B15003_025E', 'B15003_024E', 'B15003_023E', 'B15003_022E', 'B15003_021E', 'B15003_020E', 'B15003_019E', 'B15003_018E', 'B15003_017E']].sum(axis=1) / data['B15003_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME  ... pct_less_than_high_school
0  Autauga County, Alabama  ...                  0.895845
1  Baldwin County, Alabama  ...                  0.910142
2  Barbour County, Alabama  ...                  0.756710
3     Bibb County, Alabama  ...                  0.805381
4   Blount County, Alabama  ...                  0.836481

[5 rows x 5 columns]

#### Percent below poverty

In [18]:
# create a new column 'pct_below_poverty'
economic_distress_index_df['pct_below_poverty'] = data[['B17001_002E']].sum(axis=1) / data['B17001_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME  ... pct_below_poverty
0  Autauga County, Alabama  ...          0.135785
1  Baldwin County, Alabama  ...          0.092049
2  Barbour County, Alabama  ...          0.264719
3     Bibb County, Alabama  ...          0.169429
4   Blount County, Alabama  ...          0.132366

[5 rows x 6 columns]

#### Percent Unemployed

In [19]:
economic_distress_index_df['pct_unemployed'] = data[['B23025_005E']].sum(axis=1) / data['B23025_002E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME          GEO_ID  ... pct_below_poverty  pct_unemployed
0  Autauga County, Alabama  0500000US01001  ...          0.135785        0.027296
1  Baldwin County, Alabama  0500000US01003  ...          0.092049        0.036685
2  Barbour County, Alabama  0500000US01005  ...          0.264719        0.086242
3     Bibb County, Alabama  0500000US01007  ...          0.169429        0.097068
4   Blount County, Alabama  0500000US01009  ...          0.132366        0.060130

[5 rows x 7 columns]

#### Percent with cash public assistance or Food Stamps/SNAP

In [20]:
# create a new column 'pct_with_SNAP'
economic_distress_index_df['pct_with_SNAP'] = data[['B19058_002E']].sum(axis=1) / data['B19058_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME          GEO_ID  ... pct_unemployed  pct_with_SNAP
0  Autauga County, Alabama  0500000US01001  ...       0.027296       0.107980
1  Baldwin County, Alabama  0500000US01003  ...       0.036685       0.071281
2  Barbour County, Alabama  0500000US01005  ...       0.086242       0.259793
3     Bibb County, Alabama  0500000US01007  ...       0.097068       0.179585
4   Blount County, Alabama  0500000US01009  ...       0.060130       0.109061

[5 rows x 8 columns]

#### Percent with Supplemental Security Income (SSI)

In [21]:
# create a new column 'pct_with_SSI'
economic_distress_index_df['pct_with_SSI'] = data[['B19056_002E']].sum(axis=1) / data['B19056_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME          GEO_ID  ... pct_with_SNAP  pct_with_SSI
0  Autauga County, Alabama  0500000US01001  ...      0.107980      0.060624
1  Baldwin County, Alabama  0500000US01003  ...      0.071281      0.045957
2  Barbour County, Alabama  0500000US01005  ...      0.259793      0.105964
3     Bibb County, Alabama  0500000US01007  ...      0.179585      0.067768
4   Blount County, Alabama  0500000US01009  ...      0.109061      0.087418

[5 rows x 9 columns]

### Additional Percentage Calculations

##### Percent Households with less than $30,000 income (Black or African American)

In [22]:
# create a new column 'Percent_less_than_30K_Afr_Amr
economic_distress_index_df['Percent_less_than_30K_Afr_Amr'] = data[['B19001B_002E', 'B19001B_003E', 'B19001B_004E', 'B19001B_005E', 'B19001B_006E']].sum(axis=1) / data['B19001B_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME  ... Percent_less_than_30K_Afr_Amr
0  Autauga County, Alabama  ...                      0.433538
1  Baldwin County, Alabama  ...                      0.382241
2  Barbour County, Alabama  ...                      0.574405
3     Bibb County, Alabama  ...                      0.614130
4   Blount County, Alabama  ...                      0.411765

[5 rows x 10 columns]

##### Percent Households with $30,000 or less income (American Indian and Alaska Native)¶

In [23]:
# create a new column 'Percent_less_than_30K_Amr_Ind'
economic_distress_index_df['Percent_less_than_30K_Amr_Ind'] = data[['B19001C_002E', 'B19001C_003E', 'B19001C_004E', 'B19001C_005E', 'B19001C_006E']].sum(axis=1) / data['B19001C_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME  ... Percent_less_than_30K_Amr_Ind
0  Autauga County, Alabama  ...                      0.000000
1  Baldwin County, Alabama  ...                      0.379391
2  Barbour County, Alabama  ...                      0.600000
3     Bibb County, Alabama  ...                      0.000000
4   Blount County, Alabama  ...                      0.360000

[5 rows x 11 columns]

##### Percent Households with $30,000 or less income (Asian)¶

In [24]:
# create a new column 'Percent_less_than_30K_Asian'
economic_distress_index_df['Percent_less_than_30K_Asian'] = data[['B19001D_002E', 'B19001D_003E', 'B19001D_004E', 'B19001D_005E', 'B19001D_006E']].sum(axis=1) / data['B19001D_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME  ... Percent_less_than_30K_Asian
0  Autauga County, Alabama  ...                    0.094241
1  Baldwin County, Alabama  ...                    0.124606
2  Barbour County, Alabama  ...                    0.000000
3     Bibb County, Alabama  ...                    0.000000
4   Blount County, Alabama  ...                    0.000000

[5 rows x 12 columns]

##### Percent Households with $30,000 or less income (Native Hawaiian or Pacific Islander)

In [25]:
# create a new column 'Percent_less_than_30K_Nat_Haw'
economic_distress_index_df['Percent_less_than_30K_Nat_Haw'] = data[['B19001E_002E', 'B19001E_003E', 'B19001E_004E', 'B19001E_005E', 'B19001E_006E']].sum(axis=1) / data['B19001E_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME  ... Percent_less_than_30K_Nat_Haw
0  Autauga County, Alabama  ...                           NaN
1  Baldwin County, Alabama  ...                           NaN
2  Barbour County, Alabama  ...                           NaN
3     Bibb County, Alabama  ...                           NaN
4   Blount County, Alabama  ...                           NaN

[5 rows x 13 columns]

##### Percent Households wih $30,000 or less income (Nonhispanic White)

In [26]:
# create a new column 'Percent_less_than_30K_White'
economic_distress_index_df['Percent_less_than_30K_White'] = data[['B19001H_002E', 'B19001H_003E', 'B19001H_004E', 'B19001H_005E', 'B19001H_006E']].sum(axis=1) / data['B19001H_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df.head())

                      NAME  ... Percent_less_than_30K_White
0  Autauga County, Alabama  ...                    0.218005
1  Baldwin County, Alabama  ...                    0.187821
2  Barbour County, Alabama  ...                    0.303758
3     Bibb County, Alabama  ...                    0.239213
4   Blount County, Alabama  ...                    0.275835

[5 rows x 14 columns]

##### Percent Households with $30,000 or less income (Hispanic or Latino)¶

In [27]:
# create a new column 'Percent_less_than_30K_Hispanic'
economic_distress_index_df['Percent_less_than_30K_Hispanic'] = data[['B19001I_002E', 'B19001I_003E', 'B19001I_004E', 'B19001I_005E', 'B19001I_006E']].sum(axis=1) / data['B19001I_001E']


# print the first few rows of the updated dataframe to check the new column
print(economic_distress_index_df)

                                  NAME  ... Percent_less_than_30K_Hispanic
0              Autauga County, Alabama  ...                       0.147107
1              Baldwin County, Alabama  ...                       0.251799
2              Barbour County, Alabama  ...                       0.483636
3                 Bibb County, Alabama  ...                       0.169173
4               Blount County, Alabama  ...                       0.278099
...                                ...  ...                            ...
3216  Vega Baja Municipio, Puerto Rico  ...                       0.615631
3217    Vieques Municipio, Puerto Rico  ...                       0.766530
3218   Villalba Municipio, Puerto Rico  ...                       0.657959
3219    Yabucoa Municipio, Puerto Rico  ...                       0.707779
3220      Yauco Municipio, Puerto Rico  ...                       0.708665

[3221 rows x 15 columns]

In [28]:
economic_distress_index_df.head(5)

                      NAME  ... Percent_less_than_30K_Hispanic
0  Autauga County, Alabama  ...                       0.147107
1  Baldwin County, Alabama  ...                       0.251799
2  Barbour County, Alabama  ...                       0.483636
3     Bibb County, Alabama  ...                       0.169173
4   Blount County, Alabama  ...                       0.278099

[5 rows x 15 columns]

#### Download CVS to Map and/or Do Additional Analysis in Excel

In [29]:
economic_distress_index_df.to_csv("C:/Users/eli12899/Documents/ArcGIS/Projects/Economic Distress Index_County level_ACS 2021/DATA/index_econ_distress.csv")

##### Calculate Weighted Avg

In [30]:
wtavg_list = pd.read_csv("C:/Users/eli12899/Documents/ArcGIS/Projects/Economic Distress Index_County level_ACS 2021/DATA/index_econ_distress.csv")
wtavg_list.head()

   Unnamed: 0  ... Percent_less_than_30K_Hispanic
0           0  ...                       0.147107
1           1  ...                       0.251799
2           2  ...                       0.483636
3           3  ...                       0.169173
4           4  ...                       0.278099

[5 rows x 16 columns]

In [31]:
low_income= wtavg_list['pct_less_than_$30K']*1
education = wtavg_list['pct_less_than_high_school']*1
poverty = wtavg_list['pct_below_poverty']*1
unemployed = wtavg_list['pct_unemployed']*1
snap= wtavg_list['pct_with_SNAP']*1
ssi = wtavg_list['pct_with_SSI']*1


wt_df = pd.DataFrame({'a':[low_income, education, poverty, unemployed,snap, ssi],'b':[1,1,1,1,1,1]})

In [32]:
# using formula
wm_formula = (wt_df['a']).sum()/wt_df['b'].sum()
wm_formula.head(10)

wtavg_list['Priority_Score'] =wm_formula
wtavg_list.head(10)

   Unnamed: 0  ... Priority_Score
0           0  ...       0.248039
1           1  ...       0.227044
2           2  ...       0.318580
3           3  ...       0.270792
4           4  ...       0.250080
5           5  ...       0.341256
6           6  ...       0.289918
7           7  ...       0.278045
8           8  ...       0.262631
9           9  ...       0.258462

[10 rows x 17 columns]

In [38]:
weightedmean_scores_csv = "economic_distress_index_countyscore_ACS_2021.csv"

In [39]:
wtavg_list.to_csv("C:/Users/eli12899/Documents/ArcGIS/Projects/Economic Distress Index_County level_ACS 2021/DATA/economic_distress_index_countyscore_ACS_2021.csv")

In [6]:
test = pd.read_csv ("C:/Users/eli12899/Documents/ArcGIS/Projects/Economic Distress Index_County level_ACS 2021/DATA/economic_distress_index_countyscore_ACS_2021.csv")
test.head()

NameError: name 'pd' is not defined

### Create a County Feature Layer

In [5]:
econ_distress_lyr = FeatureLayer(test)

econ_distress_lyr

NameError: name 'test' is not defined

In [ ]:
demographics_df = enrich_df.loc[:,keep_cols].set_index(id_col, drop=True)

demographics_df.info()
demographics_df.head()